name: select_team
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - web/assets/
    - web/assets/Team/AFC/AFC_North/
    - web/assets/Team/AFC/AFC_West/
    - web/assets/Team/AFC/AFC_East/
    - web/assets/Team/AFC/AFC_South/
    - web/assets/Team/NFC/NFC_North/
    - web/assets/Team/NFC/NFC_West/
    - web/assets/Team/NFC/NFC_East/
    - web/assets/Team/NFC/NFC_South/
    - web/assets/winner/NFC/NFC_North/
    - web/assets/winner/NFC/NFC_West/
    - web/assets/winner/NFC/NFC_East/
    - web/assets/winner/NFC/NFC_South/
    - web/assets/winner/AFC/AFC_North/
    - web/assets/winner/AFC/AFC_West/
    - web/assets/winner/AFC/AFC_East/
    - web/assets/winner/AFC/AFC_South/
    - web/assets/svg/
    - web/assets/NFLSVG/AFC/
    - web/assets/NFLSVG/NFC/
    - web/assets/NFLSVG/NFC/North/
    - web/assets/NFLSVG/NFC/West/
    - web/assets/NFLSVG/NFC/East/
    - web/assets/NFLSVG/NFC/South/
    - web/assets/NFLSVG/AFC/North/
    - web/assets/NFLSVG/AFC/West/
    - web/assets/NFLSVG/AFC/East/
    - web/assets/NFLSVG/AFC/South/
    
  fonts:
    - family: Modak
      fonts:
        - asset: web/assets/fonts/Modak-Regular.ttf
    - family: Leckerli One
      fonts:
        - asset: web/assets/fonts/LeckerliOne-Regular.ttf