import '../AFC/AFC_East.dart';
import '../ClassTeam.dart';

final List<Team> afcEastTeams = [
  Team(
    name: Dolphins.name,
    id: Dolphins.id,
    normalImagePath: Dolphins.normalImagePath,
    winImagePath: Dolphins.winImagePath,
    mainColor: Dolphins.mainColor,
    colors: Dolphins.colors,
    division: Dolphins.division,
    conference: Dolphins.conference,
    city: Dolphins.city,
    state: Dolphins.state,
  ),
  Team(
    name: Bills.name,
    id: Bills.id,
    normalImagePath: Bills.normalImagePath,
    winImagePath: Bills.winImagePath,
    mainColor: Bills.mainColor,
    colors: Bills.colors,
    division: Bills.division,
    conference: Bills.conference,
    city: Bills.city,
    state: Bills.state,
  ),
  Team(
    name: Jets.name,
    id: Jets.id,
    normalImagePath: Jets.normalImagePath,
    winImagePath: Jets.winImagePath,
    mainColor: Jets.mainColor,
    colors: Jets.colors,
    division: Jets.division,
    conference: Jets.conference,
    city: Jets.city,
    state: Jets.state,
  ),
  Team(
    name: Patriots.name,
    id: Patriots.id,
    normalImagePath: Patriots.normalImagePath,
    winImagePath: Patriots.winImagePath,
    mainColor: Patriots.mainColor,
    colors: Patriots.colors,
    division: Patriots.division,
    conference: Patriots.conference,
    city: Patriots.city,
    state: Patriots.state,
  ),
];
